name: myrscm
description: myRscm Apps

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  rxdart: ^0.23.1
  photo_view: ^0.9.2
  flutter_webview_plugin: ^0.3.11
  intl: ^0.16.1
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  shared_preferences: ^0.5.7+3
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#icons launcher
flutter_icons:
  image_path: "assets/rscmKu_love_logo.png"
  android: "launcher_icon" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#app name
flutter_launcher_name:
  name: "RSCMKu"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/medical-billing-illustration.png
    - assets/default_error.png
    - assets/under-construction.png
    - assets/no_data.png
    - assets/doctor-appointment.png
    - assets/promo1.jpeg
    - assets/promo2.jpeg
    - assets/promo3.jpeg
    - assets/edukasi1.jpeg
    - assets/edukasi2.jpeg
    - assets/edukasi3.jpeg
    - assets/edukasi4.jpeg
    - assets/edukasi5.jpeg
    - assets/edukasi6.jpeg
    - assets/edukasi7.jpeg
    - assets/edukasi8.jpeg
    - assets/edukasi9.jpeg
    - assets/edukasi10.jpeg
    - assets/edukasi11.jpeg
    - assets/edukasi12.jpeg
    - assets/edukasi13.jpeg
    - assets/edukasi14.jpeg
    - assets/edukasi15.jpeg
    - assets/rscmKu_love_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
